__periodicTableZDict__ = {
    "1": {
        "Element": "Hydrogen",
        "Symbol": "H",
        "AtomicMass": 1.007,
        "NumberofNeutrons": 0,
        "NumberofProtons": 1,
        "NumberofElectrons": 1,
    },
    "2": {
        "Element": "Helium",
        "Symbol": "He",
        "AtomicMass": 4.002,
        "NumberofNeutrons": 2,
        "NumberofProtons": 2,
        "NumberofElectrons": 2,
    },
    "3": {
        "Element": "Lithium",
        "Symbol": "Li",
        "AtomicMass": 6.941,
        "NumberofNeutrons": 4,
        "NumberofProtons": 3,
        "NumberofElectrons": 3,
    },
    "4": {
        "Element": "Beryllium",
        "Symbol": "Be",
        "AtomicMass": 9.012,
        "NumberofNeutrons": 5,
        "NumberofProtons": 4,
        "NumberofElectrons": 4,
    },
    "5": {
        "Element": "Boron",
        "Symbol": "B",
        "AtomicMass": 10.811,
        "NumberofNeutrons": 6,
        "NumberofProtons": 5,
        "NumberofElectrons": 5,
    },
    "6": {
        "Element": "Carbon",
        "Symbol": "C",
        "AtomicMass": 12.011,
        "NumberofNeutrons": 6,
        "NumberofProtons": 6,
        "NumberofElectrons": 6,
    },
    "7": {
        "Element": "Nitrogen",
        "Symbol": "N",
        "AtomicMass": 14.007,
        "NumberofNeutrons": 7,
        "NumberofProtons": 7,
        "NumberofElectrons": 7,
    },
    "8": {
        "Element": "Oxygen",
        "Symbol": "O",
        "AtomicMass": 15.999,
        "NumberofNeutrons": 8,
        "NumberofProtons": 8,
        "NumberofElectrons": 8,
    },
    "9": {
        "Element": "Fluorine",
        "Symbol": "F",
        "AtomicMass": 18.998,
        "NumberofNeutrons": 10,
        "NumberofProtons": 9,
        "NumberofElectrons": 9,
    },
    "10": {
        "Element": "Neon",
        "Symbol": "Ne",
        "AtomicMass": 20.18,
        "NumberofNeutrons": 10,
        "NumberofProtons": 10,
        "NumberofElectrons": 10,
    },
    "11": {
        "Element": "Sodium",
        "Symbol": "Na",
        "AtomicMass": 22.99,
        "NumberofNeutrons": 12,
        "NumberofProtons": 11,
        "NumberofElectrons": 11,
    },
    "12": {
        "Element": "Magnesium",
        "Symbol": "Mg",
        "AtomicMass": 24.305,
        "NumberofNeutrons": 12,
        "NumberofProtons": 12,
        "NumberofElectrons": 12,
    },
    "13": {
        "Element": "Aluminum",
        "Symbol": "Al",
        "AtomicMass": 26.982,
        "NumberofNeutrons": 14,
        "NumberofProtons": 13,
        "NumberofElectrons": 13,
    },
    "14": {
        "Element": "Silicon",
        "Symbol": "Si",
        "AtomicMass": 28.086,
        "NumberofNeutrons": 14,
        "NumberofProtons": 14,
        "NumberofElectrons": 14,
    },
    "15": {
        "Element": "Phosphorus",
        "Symbol": "P",
        "AtomicMass": 30.974,
        "NumberofNeutrons": 16,
        "NumberofProtons": 15,
        "NumberofElectrons": 15,
    },
    "16": {
        "Element": "Sulfur",
        "Symbol": "S",
        "AtomicMass": 32.065,
        "NumberofNeutrons": 16,
        "NumberofProtons": 16,
        "NumberofElectrons": 16,
    },
    "17": {
        "Element": "Chlorine",
        "Symbol": "Cl",
        "AtomicMass": 35.453,
        "NumberofNeutrons": 18,
        "NumberofProtons": 17,
        "NumberofElectrons": 17,
    },
    "18": {
        "Element": "Argon",
        "Symbol": "Ar",
        "AtomicMass": 39.948,
        "NumberofNeutrons": 22,
        "NumberofProtons": 18,
        "NumberofElectrons": 18,
    },
    "19": {
        "Element": "Potassium",
        "Symbol": "K",
        "AtomicMass": 39.098,
        "NumberofNeutrons": 20,
        "NumberofProtons": 19,
        "NumberofElectrons": 19,
    },
    "20": {
        "Element": "Calcium",
        "Symbol": "Ca",
        "AtomicMass": 40.078,
        "NumberofNeutrons": 20,
        "NumberofProtons": 20,
        "NumberofElectrons": 20,
    },
    "21": {
        "Element": "Scandium",
        "Symbol": "Sc",
        "AtomicMass": 44.956,
        "NumberofNeutrons": 24,
        "NumberofProtons": 21,
        "NumberofElectrons": 21,
    },
    "22": {
        "Element": "Titanium",
        "Symbol": "Ti",
        "AtomicMass": 47.867,
        "NumberofNeutrons": 26,
        "NumberofProtons": 22,
        "NumberofElectrons": 22,
    },
    "23": {
        "Element": "Vanadium",
        "Symbol": "V",
        "AtomicMass": 50.942,
        "NumberofNeutrons": 28,
        "NumberofProtons": 23,
        "NumberofElectrons": 23,
    },
    "24": {
        "Element": "Chromium",
        "Symbol": "Cr",
        "AtomicMass": 51.996,
        "NumberofNeutrons": 28,
        "NumberofProtons": 24,
        "NumberofElectrons": 24,
    },
    "25": {
        "Element": "Manganese",
        "Symbol": "Mn",
        "AtomicMass": 54.938,
        "NumberofNeutrons": 30,
        "NumberofProtons": 25,
        "NumberofElectrons": 25,
    },
    "26": {
        "Element": "Iron",
        "Symbol": "Fe",
        "AtomicMass": 55.845,
        "NumberofNeutrons": 30,
        "NumberofProtons": 26,
        "NumberofElectrons": 26,
    },
    "27": {
        "Element": "Cobalt",
        "Symbol": "Co",
        "AtomicMass": 58.933,
        "NumberofNeutrons": 32,
        "NumberofProtons": 27,
        "NumberofElectrons": 27,
    },
    "28": {
        "Element": "Nickel",
        "Symbol": "Ni",
        "AtomicMass": 58.693,
        "NumberofNeutrons": 31,
        "NumberofProtons": 28,
        "NumberofElectrons": 28,
    },
    "29": {
        "Element": "Copper",
        "Symbol": "Cu",
        "AtomicMass": 63.546,
        "NumberofNeutrons": 35,
        "NumberofProtons": 29,
        "NumberofElectrons": 29,
    },
    "30": {
        "Element": "Zinc",
        "Symbol": "Zn",
        "AtomicMass": 65.38,
        "NumberofNeutrons": 35,
        "NumberofProtons": 30,
        "NumberofElectrons": 30,
    },
    "31": {
        "Element": "Gallium",
        "Symbol": "Ga",
        "AtomicMass": 69.723,
        "NumberofNeutrons": 39,
        "NumberofProtons": 31,
        "NumberofElectrons": 31,
    },
    "32": {
        "Element": "Germanium",
        "Symbol": "Ge",
        "AtomicMass": 72.64,
        "NumberofNeutrons": 41,
        "NumberofProtons": 32,
        "NumberofElectrons": 32,
    },
    "33": {
        "Element": "Arsenic",
        "Symbol": "As",
        "AtomicMass": 74.922,
        "NumberofNeutrons": 42,
        "NumberofProtons": 33,
        "NumberofElectrons": 33,
    },
    "34": {
        "Element": "Selenium",
        "Symbol": "Se",
        "AtomicMass": 78.96,
        "NumberofNeutrons": 45,
        "NumberofProtons": 34,
        "NumberofElectrons": 34,
    },
    "35": {
        "Element": "Bromine",
        "Symbol": "Br",
        "AtomicMass": 79.904,
        "NumberofNeutrons": 45,
        "NumberofProtons": 35,
        "NumberofElectrons": 35,
    },
    "36": {
        "Element": "Krypton",
        "Symbol": "Kr",
        "AtomicMass": 83.798,
        "NumberofNeutrons": 48,
        "NumberofProtons": 36,
        "NumberofElectrons": 36,
    },
    "37": {
        "Element": "Rubidium",
        "Symbol": "Rb",
        "AtomicMass": 85.468,
        "NumberofNeutrons": 48,
        "NumberofProtons": 37,
        "NumberofElectrons": 37,
    },
    "38": {
        "Element": "Strontium",
        "Symbol": "Sr",
        "AtomicMass": 87.62,
        "NumberofNeutrons": 50,
        "NumberofProtons": 38,
        "NumberofElectrons": 38,
    },
    "39": {
        "Element": "Yttrium",
        "Symbol": "Y",
        "AtomicMass": 88.906,
        "NumberofNeutrons": 50,
        "NumberofProtons": 39,
        "NumberofElectrons": 39,
    },
    "40": {
        "Element": "Zirconium",
        "Symbol": "Zr",
        "AtomicMass": 91.224,
        "NumberofNeutrons": 51,
        "NumberofProtons": 40,
        "NumberofElectrons": 40,
    },
    "41": {
        "Element": "Niobium",
        "Symbol": "Nb",
        "AtomicMass": 92.906,
        "NumberofNeutrons": 52,
        "NumberofProtons": 41,
        "NumberofElectrons": 41,
    },
    "42": {
        "Element": "Molybdenum",
        "Symbol": "Mo",
        "AtomicMass": 95.96,
        "NumberofNeutrons": 54,
        "NumberofProtons": 42,
        "NumberofElectrons": 42,
    },
    "43": {
        "Element": "Technetium",
        "Symbol": "Tc",
        "AtomicMass": 98.0,
        "NumberofNeutrons": 55,
        "NumberofProtons": 43,
        "NumberofElectrons": 43,
    },
    "44": {
        "Element": "Ruthenium",
        "Symbol": "Ru",
        "AtomicMass": 101.07,
        "NumberofNeutrons": 57,
        "NumberofProtons": 44,
        "NumberofElectrons": 44,
    },
    "45": {
        "Element": "Rhodium",
        "Symbol": "Rh",
        "AtomicMass": 102.906,
        "NumberofNeutrons": 58,
        "NumberofProtons": 45,
        "NumberofElectrons": 45,
    },
    "46": {
        "Element": "Palladium",
        "Symbol": "Pd",
        "AtomicMass": 106.42,
        "NumberofNeutrons": 60,
        "NumberofProtons": 46,
        "NumberofElectrons": 46,
    },
    "47": {
        "Element": "Silver",
        "Symbol": "Ag",
        "AtomicMass": 107.868,
        "NumberofNeutrons": 61,
        "NumberofProtons": 47,
        "NumberofElectrons": 47,
    },
    "48": {
        "Element": "Cadmium",
        "Symbol": "Cd",
        "AtomicMass": 112.411,
        "NumberofNeutrons": 64,
        "NumberofProtons": 48,
        "NumberofElectrons": 48,
    },
    "49": {
        "Element": "Indium",
        "Symbol": "In",
        "AtomicMass": 114.818,
        "NumberofNeutrons": 66,
        "NumberofProtons": 49,
        "NumberofElectrons": 49,
    },
    "50": {
        "Element": "Tin",
        "Symbol": "Sn",
        "AtomicMass": 118.71,
        "NumberofNeutrons": 69,
        "NumberofProtons": 50,
        "NumberofElectrons": 50,
    },
    "51": {
        "Element": "Antimony",
        "Symbol": "Sb",
        "AtomicMass": 121.76,
        "NumberofNeutrons": 71,
        "NumberofProtons": 51,
        "NumberofElectrons": 51,
    },
    "52": {
        "Element": "Tellurium",
        "Symbol": "Te",
        "AtomicMass": 127.6,
        "NumberofNeutrons": 76,
        "NumberofProtons": 52,
        "NumberofElectrons": 52,
    },
    "53": {
        "Element": "Iodine",
        "Symbol": "I",
        "AtomicMass": 126.904,
        "NumberofNeutrons": 74,
        "NumberofProtons": 53,
        "NumberofElectrons": 53,
    },
    "54": {
        "Element": "Xenon",
        "Symbol": "Xe",
        "AtomicMass": 131.293,
        "NumberofNeutrons": 77,
        "NumberofProtons": 54,
        "NumberofElectrons": 54,
    },
    "55": {
        "Element": "Cesium",
        "Symbol": "Cs",
        "AtomicMass": 132.905,
        "NumberofNeutrons": 78,
        "NumberofProtons": 55,
        "NumberofElectrons": 55,
    },
    "56": {
        "Element": "Barium",
        "Symbol": "Ba",
        "AtomicMass": 137.327,
        "NumberofNeutrons": 81,
        "NumberofProtons": 56,
        "NumberofElectrons": 56,
    },
    "57": {
        "Element": "Lanthanum",
        "Symbol": "La",
        "AtomicMass": 138.905,
        "NumberofNeutrons": 82,
        "NumberofProtons": 57,
        "NumberofElectrons": 57,
    },
    "58": {
        "Element": "Cerium",
        "Symbol": "Ce",
        "AtomicMass": 140.116,
        "NumberofNeutrons": 82,
        "NumberofProtons": 58,
        "NumberofElectrons": 58,
    },
    "59": {
        "Element": "Praseodymium",
        "Symbol": "Pr",
        "AtomicMass": 140.908,
        "NumberofNeutrons": 82,
        "NumberofProtons": 59,
        "NumberofElectrons": 59,
    },
    "60": {
        "Element": "Neodymium",
        "Symbol": "Nd",
        "AtomicMass": 144.242,
        "NumberofNeutrons": 84,
        "NumberofProtons": 60,
        "NumberofElectrons": 60,
    },
    "61": {
        "Element": "Promethium",
        "Symbol": "Pm",
        "AtomicMass": 145.0,
        "NumberofNeutrons": 84,
        "NumberofProtons": 61,
        "NumberofElectrons": 61,
    },
    "62": {
        "Element": "Samarium",
        "Symbol": "Sm",
        "AtomicMass": 150.36,
        "NumberofNeutrons": 88,
        "NumberofProtons": 62,
        "NumberofElectrons": 62,
    },
    "63": {
        "Element": "Europium",
        "Symbol": "Eu",
        "AtomicMass": 151.964,
        "NumberofNeutrons": 89,
        "NumberofProtons": 63,
        "NumberofElectrons": 63,
    },
    "64": {
        "Element": "Gadolinium",
        "Symbol": "Gd",
        "AtomicMass": 157.25,
        "NumberofNeutrons": 93,
        "NumberofProtons": 64,
        "NumberofElectrons": 64,
    },
    "65": {
        "Element": "Terbium",
        "Symbol": "Tb",
        "AtomicMass": 158.925,
        "NumberofNeutrons": 94,
        "NumberofProtons": 65,
        "NumberofElectrons": 65,
    },
    "66": {
        "Element": "Dysprosium",
        "Symbol": "Dy",
        "AtomicMass": 162.5,
        "NumberofNeutrons": 97,
        "NumberofProtons": 66,
        "NumberofElectrons": 66,
    },
    "67": {
        "Element": "Holmium",
        "Symbol": "Ho",
        "AtomicMass": 164.93,
        "NumberofNeutrons": 98,
        "NumberofProtons": 67,
        "NumberofElectrons": 67,
    },
    "68": {
        "Element": "Erbium",
        "Symbol": "Er",
        "AtomicMass": 167.259,
        "NumberofNeutrons": 99,
        "NumberofProtons": 68,
        "NumberofElectrons": 68,
    },
    "69": {
        "Element": "Thulium",
        "Symbol": "Tm",
        "AtomicMass": 168.934,
        "NumberofNeutrons": 100,
        "NumberofProtons": 69,
        "NumberofElectrons": 69,
    },
    "70": {
        "Element": "Ytterbium",
        "Symbol": "Yb",
        "AtomicMass": 173.054,
        "NumberofNeutrons": 103,
        "NumberofProtons": 70,
        "NumberofElectrons": 70,
    },
    "71": {
        "Element": "Lutetium",
        "Symbol": "Lu",
        "AtomicMass": 174.967,
        "NumberofNeutrons": 104,
        "NumberofProtons": 71,
        "NumberofElectrons": 71,
    },
    "72": {
        "Element": "Hafnium",
        "Symbol": "Hf",
        "AtomicMass": 178.49,
        "NumberofNeutrons": 106,
        "NumberofProtons": 72,
        "NumberofElectrons": 72,
    },
    "73": {
        "Element": "Tantalum",
        "Symbol": "Ta",
        "AtomicMass": 180.948,
        "NumberofNeutrons": 108,
        "NumberofProtons": 73,
        "NumberofElectrons": 73,
    },
    "74": {
        "Element": "Wolfram",
        "Symbol": "W",
        "AtomicMass": 183.84,
        "NumberofNeutrons": 110,
        "NumberofProtons": 74,
        "NumberofElectrons": 74,
    },
    "75": {
        "Element": "Rhenium",
        "Symbol": "Re",
        "AtomicMass": 186.207,
        "NumberofNeutrons": 111,
        "NumberofProtons": 75,
        "NumberofElectrons": 75,
    },
    "76": {
        "Element": "Osmium",
        "Symbol": "Os",
        "AtomicMass": 190.23,
        "NumberofNeutrons": 114,
        "NumberofProtons": 76,
        "NumberofElectrons": 76,
    },
    "77": {
        "Element": "Iridium",
        "Symbol": "Ir",
        "AtomicMass": 192.217,
        "NumberofNeutrons": 115,
        "NumberofProtons": 77,
        "NumberofElectrons": 77,
    },
    "78": {
        "Element": "Platinum",
        "Symbol": "Pt",
        "AtomicMass": 195.084,
        "NumberofNeutrons": 117,
        "NumberofProtons": 78,
        "NumberofElectrons": 78,
    },
    "79": {
        "Element": "Gold",
        "Symbol": "Au",
        "AtomicMass": 196.967,
        "NumberofNeutrons": 118,
        "NumberofProtons": 79,
        "NumberofElectrons": 79,
    },
    "80": {
        "Element": "Mercury",
        "Symbol": "Hg",
        "AtomicMass": 200.59,
        "NumberofNeutrons": 121,
        "NumberofProtons": 80,
        "NumberofElectrons": 80,
    },
    "81": {
        "Element": "Thallium",
        "Symbol": "Tl",
        "AtomicMass": 204.383,
        "NumberofNeutrons": 123,
        "NumberofProtons": 81,
        "NumberofElectrons": 81,
    },
    "82": {
        "Element": "Lead",
        "Symbol": "Pb",
        "AtomicMass": 207.2,
        "NumberofNeutrons": 125,
        "NumberofProtons": 82,
        "NumberofElectrons": 82,
    },
    "83": {
        "Element": "Bismuth",
        "Symbol": "Bi",
        "AtomicMass": 208.98,
        "NumberofNeutrons": 126,
        "NumberofProtons": 83,
        "NumberofElectrons": 83,
    },
    "84": {
        "Element": "Polonium",
        "Symbol": "Po",
        "AtomicMass": 210.0,
        "NumberofNeutrons": 126,
        "NumberofProtons": 84,
        "NumberofElectrons": 84,
    },
    "85": {
        "Element": "Astatine",
        "Symbol": "At",
        "AtomicMass": 210.0,
        "NumberofNeutrons": 125,
        "NumberofProtons": 85,
        "NumberofElectrons": 85,
    },
    "86": {
        "Element": "Radon",
        "Symbol": "Rn",
        "AtomicMass": 222.0,
        "NumberofNeutrons": 136,
        "NumberofProtons": 86,
        "NumberofElectrons": 86,
    },
    "87": {
        "Element": "Francium",
        "Symbol": "Fr",
        "AtomicMass": 223.0,
        "NumberofNeutrons": 136,
        "NumberofProtons": 87,
        "NumberofElectrons": 87,
    },
    "88": {
        "Element": "Radium",
        "Symbol": "Ra",
        "AtomicMass": 226.0,
        "NumberofNeutrons": 138,
        "NumberofProtons": 88,
        "NumberofElectrons": 88,
    },
    "89": {
        "Element": "Actinium",
        "Symbol": "Ac",
        "AtomicMass": 227.0,
        "NumberofNeutrons": 138,
        "NumberofProtons": 89,
        "NumberofElectrons": 89,
    },
    "90": {
        "Element": "Thorium",
        "Symbol": "Th",
        "AtomicMass": 232.038,
        "NumberofNeutrons": 142,
        "NumberofProtons": 90,
        "NumberofElectrons": 90,
    },
    "91": {
        "Element": "Protactinium",
        "Symbol": "Pa",
        "AtomicMass": 231.036,
        "NumberofNeutrons": 140,
        "NumberofProtons": 91,
        "NumberofElectrons": 91,
    },
    "92": {
        "Element": "Uranium",
        "Symbol": "U",
        "AtomicMass": 238.029,
        "NumberofNeutrons": 146,
        "NumberofProtons": 92,
        "NumberofElectrons": 92,
    },
    "93": {
        "Element": "Neptunium",
        "Symbol": "Np",
        "AtomicMass": 237.0,
        "NumberofNeutrons": 144,
        "NumberofProtons": 93,
        "NumberofElectrons": 93,
    },
    "94": {
        "Element": "Plutonium",
        "Symbol": "Pu",
        "AtomicMass": 244.0,
        "NumberofNeutrons": 150,
        "NumberofProtons": 94,
        "NumberofElectrons": 94,
    },
    "95": {
        "Element": "Americium",
        "Symbol": "Am",
        "AtomicMass": 243.0,
        "NumberofNeutrons": 148,
        "NumberofProtons": 95,
        "NumberofElectrons": 95,
    },
    "96": {
        "Element": "Curium",
        "Symbol": "Cm",
        "AtomicMass": 247.0,
        "NumberofNeutrons": 151,
        "NumberofProtons": 96,
        "NumberofElectrons": 96,
    },
    "97": {
        "Element": "Berkelium",
        "Symbol": "Bk",
        "AtomicMass": 247.0,
        "NumberofNeutrons": 150,
        "NumberofProtons": 97,
        "NumberofElectrons": 97,
    },
    "98": {
        "Element": "Californium",
        "Symbol": "Cf",
        "AtomicMass": 251.0,
        "NumberofNeutrons": 153,
        "NumberofProtons": 98,
        "NumberofElectrons": 98,
    },
    "99": {
        "Element": "Einsteinium",
        "Symbol": "Es",
        "AtomicMass": 252.0,
        "NumberofNeutrons": 153,
        "NumberofProtons": 99,
        "NumberofElectrons": 99,
    },
    "100": {
        "Element": "Fermium",
        "Symbol": "Fm",
        "AtomicMass": 257.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 100,
        "NumberofElectrons": 100,
    },
    "101": {
        "Element": "Mendelevium",
        "Symbol": "Md",
        "AtomicMass": 258.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 101,
        "NumberofElectrons": 101,
    },
    "102": {
        "Element": "Nobelium",
        "Symbol": "No",
        "AtomicMass": 259.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 102,
        "NumberofElectrons": 102,
    },
    "103": {
        "Element": "Lawrencium",
        "Symbol": "Lr",
        "AtomicMass": 262.0,
        "NumberofNeutrons": 159,
        "NumberofProtons": 103,
        "NumberofElectrons": 103,
    },
    "104": {
        "Element": "Rutherfordium",
        "Symbol": "Rf",
        "AtomicMass": 261.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 104,
        "NumberofElectrons": 104,
    },
    "105": {
        "Element": "Dubnium",
        "Symbol": "Db",
        "AtomicMass": 262.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 105,
        "NumberofElectrons": 105,
    },
    "106": {
        "Element": "Seaborgium",
        "Symbol": "Sg",
        "AtomicMass": 266.0,
        "NumberofNeutrons": 160,
        "NumberofProtons": 106,
        "NumberofElectrons": 106,
    },
    "107": {
        "Element": "Bohrium",
        "Symbol": "Bh",
        "AtomicMass": 264.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 107,
        "NumberofElectrons": 107,
    },
    "108": {
        "Element": "Hassium",
        "Symbol": "Hs",
        "AtomicMass": 267.0,
        "NumberofNeutrons": 159,
        "NumberofProtons": 108,
        "NumberofElectrons": 108,
    },
    "109": {
        "Element": "Meitnerium",
        "Symbol": "Mt",
        "AtomicMass": 268.0,
        "NumberofNeutrons": 159,
        "NumberofProtons": 109,
        "NumberofElectrons": 109,
    },
    "110": {
        "Element": "Darmstadtium ",
        "Symbol": "Ds ",
        "AtomicMass": 271.0,
        "NumberofNeutrons": 161,
        "NumberofProtons": 110,
        "NumberofElectrons": 110,
    },
    "111": {
        "Element": "Roentgenium ",
        "Symbol": "Rg ",
        "AtomicMass": 272.0,
        "NumberofNeutrons": 161,
        "NumberofProtons": 111,
        "NumberofElectrons": 111,
    },
    "112": {
        "Element": "Copernicium ",
        "Symbol": "Cn ",
        "AtomicMass": 285.0,
        "NumberofNeutrons": 173,
        "NumberofProtons": 112,
        "NumberofElectrons": 112,
    },
    "113": {
        "Element": "Nihonium",
        "Symbol": "Nh",
        "AtomicMass": 284.0,
        "NumberofNeutrons": 171,
        "NumberofProtons": 113,
        "NumberofElectrons": 113,
    },
    "114": {
        "Element": "Flerovium",
        "Symbol": "Fl",
        "AtomicMass": 289.0,
        "NumberofNeutrons": 175,
        "NumberofProtons": 114,
        "NumberofElectrons": 114,
    },
    "115": {
        "Element": "Moscovium",
        "Symbol": "Mc",
        "AtomicMass": 288.0,
        "NumberofNeutrons": 173,
        "NumberofProtons": 115,
        "NumberofElectrons": 115,
    },
    "116": {
        "Element": "Livermorium",
        "Symbol": "Lv",
        "AtomicMass": 292.0,
        "NumberofNeutrons": 176,
        "NumberofProtons": 116,
        "NumberofElectrons": 116,
    },
    "117": {
        "Element": "Tennessine",
        "Symbol": "Ts",
        "AtomicMass": 295.0,
        "NumberofNeutrons": 178,
        "NumberofProtons": 117,
        "NumberofElectrons": 117,
    },
    "118": {
        "Element": "Oganesson",
        "Symbol": "Og",
        "AtomicMass": 294.0,
        "NumberofNeutrons": 176,
        "NumberofProtons": 118,
        "NumberofElectrons": 118,
    },
}


__periodicTableSymbolDict_ = {
    "H": {
        "AtomicNumber": 1,
        "Element": "Hydrogen",
        "AtomicMass": 1.007,
        "NumberofNeutrons": 0,
        "NumberofProtons": 1,
        "NumberofElectrons": 1,
    },
    "He": {
        "AtomicNumber": 2,
        "Element": "Helium",
        "AtomicMass": 4.002,
        "NumberofNeutrons": 2,
        "NumberofProtons": 2,
        "NumberofElectrons": 2,
    },
    "Li": {
        "AtomicNumber": 3,
        "Element": "Lithium",
        "AtomicMass": 6.941,
        "NumberofNeutrons": 4,
        "NumberofProtons": 3,
        "NumberofElectrons": 3,
    },
    "Be": {
        "AtomicNumber": 4,
        "Element": "Beryllium",
        "AtomicMass": 9.012,
        "NumberofNeutrons": 5,
        "NumberofProtons": 4,
        "NumberofElectrons": 4,
    },
    "B": {
        "AtomicNumber": 5,
        "Element": "Boron",
        "AtomicMass": 10.811,
        "NumberofNeutrons": 6,
        "NumberofProtons": 5,
        "NumberofElectrons": 5,
    },
    "C": {
        "AtomicNumber": 6,
        "Element": "Carbon",
        "AtomicMass": 12.011,
        "NumberofNeutrons": 6,
        "NumberofProtons": 6,
        "NumberofElectrons": 6,
    },
    "N": {
        "AtomicNumber": 7,
        "Element": "Nitrogen",
        "AtomicMass": 14.007,
        "NumberofNeutrons": 7,
        "NumberofProtons": 7,
        "NumberofElectrons": 7,
    },
    "O": {
        "AtomicNumber": 8,
        "Element": "Oxygen",
        "AtomicMass": 15.999,
        "NumberofNeutrons": 8,
        "NumberofProtons": 8,
        "NumberofElectrons": 8,
    },
    "F": {
        "AtomicNumber": 9,
        "Element": "Fluorine",
        "AtomicMass": 18.998,
        "NumberofNeutrons": 10,
        "NumberofProtons": 9,
        "NumberofElectrons": 9,
    },
    "Ne": {
        "AtomicNumber": 10,
        "Element": "Neon",
        "AtomicMass": 20.18,
        "NumberofNeutrons": 10,
        "NumberofProtons": 10,
        "NumberofElectrons": 10,
    },
    "Na": {
        "AtomicNumber": 11,
        "Element": "Sodium",
        "AtomicMass": 22.99,
        "NumberofNeutrons": 12,
        "NumberofProtons": 11,
        "NumberofElectrons": 11,
    },
    "Mg": {
        "AtomicNumber": 12,
        "Element": "Magnesium",
        "AtomicMass": 24.305,
        "NumberofNeutrons": 12,
        "NumberofProtons": 12,
        "NumberofElectrons": 12,
    },
    "Al": {
        "AtomicNumber": 13,
        "Element": "Aluminum",
        "AtomicMass": 26.982,
        "NumberofNeutrons": 14,
        "NumberofProtons": 13,
        "NumberofElectrons": 13,
    },
    "Si": {
        "AtomicNumber": 14,
        "Element": "Silicon",
        "AtomicMass": 28.086,
        "NumberofNeutrons": 14,
        "NumberofProtons": 14,
        "NumberofElectrons": 14,
    },
    "P": {
        "AtomicNumber": 15,
        "Element": "Phosphorus",
        "AtomicMass": 30.974,
        "NumberofNeutrons": 16,
        "NumberofProtons": 15,
        "NumberofElectrons": 15,
    },
    "S": {
        "AtomicNumber": 16,
        "Element": "Sulfur",
        "AtomicMass": 32.065,
        "NumberofNeutrons": 16,
        "NumberofProtons": 16,
        "NumberofElectrons": 16,
    },
    "Cl": {
        "AtomicNumber": 17,
        "Element": "Chlorine",
        "AtomicMass": 35.453,
        "NumberofNeutrons": 18,
        "NumberofProtons": 17,
        "NumberofElectrons": 17,
    },
    "Ar": {
        "AtomicNumber": 18,
        "Element": "Argon",
        "AtomicMass": 39.948,
        "NumberofNeutrons": 22,
        "NumberofProtons": 18,
        "NumberofElectrons": 18,
    },
    "K": {
        "AtomicNumber": 19,
        "Element": "Potassium",
        "AtomicMass": 39.098,
        "NumberofNeutrons": 20,
        "NumberofProtons": 19,
        "NumberofElectrons": 19,
    },
    "Ca": {
        "AtomicNumber": 20,
        "Element": "Calcium",
        "AtomicMass": 40.078,
        "NumberofNeutrons": 20,
        "NumberofProtons": 20,
        "NumberofElectrons": 20,
    },
    "Sc": {
        "AtomicNumber": 21,
        "Element": "Scandium",
        "AtomicMass": 44.956,
        "NumberofNeutrons": 24,
        "NumberofProtons": 21,
        "NumberofElectrons": 21,
    },
    "Ti": {
        "AtomicNumber": 22,
        "Element": "Titanium",
        "AtomicMass": 47.867,
        "NumberofNeutrons": 26,
        "NumberofProtons": 22,
        "NumberofElectrons": 22,
    },
    "V": {
        "AtomicNumber": 23,
        "Element": "Vanadium",
        "AtomicMass": 50.942,
        "NumberofNeutrons": 28,
        "NumberofProtons": 23,
        "NumberofElectrons": 23,
    },
    "Cr": {
        "AtomicNumber": 24,
        "Element": "Chromium",
        "AtomicMass": 51.996,
        "NumberofNeutrons": 28,
        "NumberofProtons": 24,
        "NumberofElectrons": 24,
    },
    "Mn": {
        "AtomicNumber": 25,
        "Element": "Manganese",
        "AtomicMass": 54.938,
        "NumberofNeutrons": 30,
        "NumberofProtons": 25,
        "NumberofElectrons": 25,
    },
    "Fe": {
        "AtomicNumber": 26,
        "Element": "Iron",
        "AtomicMass": 55.845,
        "NumberofNeutrons": 30,
        "NumberofProtons": 26,
        "NumberofElectrons": 26,
    },
    "Co": {
        "AtomicNumber": 27,
        "Element": "Cobalt",
        "AtomicMass": 58.933,
        "NumberofNeutrons": 32,
        "NumberofProtons": 27,
        "NumberofElectrons": 27,
    },
    "Ni": {
        "AtomicNumber": 28,
        "Element": "Nickel",
        "AtomicMass": 58.693,
        "NumberofNeutrons": 31,
        "NumberofProtons": 28,
        "NumberofElectrons": 28,
    },
    "Cu": {
        "AtomicNumber": 29,
        "Element": "Copper",
        "AtomicMass": 63.546,
        "NumberofNeutrons": 35,
        "NumberofProtons": 29,
        "NumberofElectrons": 29,
    },
    "Zn": {
        "AtomicNumber": 30,
        "Element": "Zinc",
        "AtomicMass": 65.38,
        "NumberofNeutrons": 35,
        "NumberofProtons": 30,
        "NumberofElectrons": 30,
    },
    "Ga": {
        "AtomicNumber": 31,
        "Element": "Gallium",
        "AtomicMass": 69.723,
        "NumberofNeutrons": 39,
        "NumberofProtons": 31,
        "NumberofElectrons": 31,
    },
    "Ge": {
        "AtomicNumber": 32,
        "Element": "Germanium",
        "AtomicMass": 72.64,
        "NumberofNeutrons": 41,
        "NumberofProtons": 32,
        "NumberofElectrons": 32,
    },
    "As": {
        "AtomicNumber": 33,
        "Element": "Arsenic",
        "AtomicMass": 74.922,
        "NumberofNeutrons": 42,
        "NumberofProtons": 33,
        "NumberofElectrons": 33,
    },
    "Se": {
        "AtomicNumber": 34,
        "Element": "Selenium",
        "AtomicMass": 78.96,
        "NumberofNeutrons": 45,
        "NumberofProtons": 34,
        "NumberofElectrons": 34,
    },
    "Br": {
        "AtomicNumber": 35,
        "Element": "Bromine",
        "AtomicMass": 79.904,
        "NumberofNeutrons": 45,
        "NumberofProtons": 35,
        "NumberofElectrons": 35,
    },
    "Kr": {
        "AtomicNumber": 36,
        "Element": "Krypton",
        "AtomicMass": 83.798,
        "NumberofNeutrons": 48,
        "NumberofProtons": 36,
        "NumberofElectrons": 36,
    },
    "Rb": {
        "AtomicNumber": 37,
        "Element": "Rubidium",
        "AtomicMass": 85.468,
        "NumberofNeutrons": 48,
        "NumberofProtons": 37,
        "NumberofElectrons": 37,
    },
    "Sr": {
        "AtomicNumber": 38,
        "Element": "Strontium",
        "AtomicMass": 87.62,
        "NumberofNeutrons": 50,
        "NumberofProtons": 38,
        "NumberofElectrons": 38,
    },
    "Y": {
        "AtomicNumber": 39,
        "Element": "Yttrium",
        "AtomicMass": 88.906,
        "NumberofNeutrons": 50,
        "NumberofProtons": 39,
        "NumberofElectrons": 39,
    },
    "Zr": {
        "AtomicNumber": 40,
        "Element": "Zirconium",
        "AtomicMass": 91.224,
        "NumberofNeutrons": 51,
        "NumberofProtons": 40,
        "NumberofElectrons": 40,
    },
    "Nb": {
        "AtomicNumber": 41,
        "Element": "Niobium",
        "AtomicMass": 92.906,
        "NumberofNeutrons": 52,
        "NumberofProtons": 41,
        "NumberofElectrons": 41,
    },
    "Mo": {
        "AtomicNumber": 42,
        "Element": "Molybdenum",
        "AtomicMass": 95.96,
        "NumberofNeutrons": 54,
        "NumberofProtons": 42,
        "NumberofElectrons": 42,
    },
    "Tc": {
        "AtomicNumber": 43,
        "Element": "Technetium",
        "AtomicMass": 98.0,
        "NumberofNeutrons": 55,
        "NumberofProtons": 43,
        "NumberofElectrons": 43,
    },
    "Ru": {
        "AtomicNumber": 44,
        "Element": "Ruthenium",
        "AtomicMass": 101.07,
        "NumberofNeutrons": 57,
        "NumberofProtons": 44,
        "NumberofElectrons": 44,
    },
    "Rh": {
        "AtomicNumber": 45,
        "Element": "Rhodium",
        "AtomicMass": 102.906,
        "NumberofNeutrons": 58,
        "NumberofProtons": 45,
        "NumberofElectrons": 45,
    },
    "Pd": {
        "AtomicNumber": 46,
        "Element": "Palladium",
        "AtomicMass": 106.42,
        "NumberofNeutrons": 60,
        "NumberofProtons": 46,
        "NumberofElectrons": 46,
    },
    "Ag": {
        "AtomicNumber": 47,
        "Element": "Silver",
        "AtomicMass": 107.868,
        "NumberofNeutrons": 61,
        "NumberofProtons": 47,
        "NumberofElectrons": 47,
    },
    "Cd": {
        "AtomicNumber": 48,
        "Element": "Cadmium",
        "AtomicMass": 112.411,
        "NumberofNeutrons": 64,
        "NumberofProtons": 48,
        "NumberofElectrons": 48,
    },
    "In": {
        "AtomicNumber": 49,
        "Element": "Indium",
        "AtomicMass": 114.818,
        "NumberofNeutrons": 66,
        "NumberofProtons": 49,
        "NumberofElectrons": 49,
    },
    "Sn": {
        "AtomicNumber": 50,
        "Element": "Tin",
        "AtomicMass": 118.71,
        "NumberofNeutrons": 69,
        "NumberofProtons": 50,
        "NumberofElectrons": 50,
    },
    "Sb": {
        "AtomicNumber": 51,
        "Element": "Antimony",
        "AtomicMass": 121.76,
        "NumberofNeutrons": 71,
        "NumberofProtons": 51,
        "NumberofElectrons": 51,
    },
    "Te": {
        "AtomicNumber": 52,
        "Element": "Tellurium",
        "AtomicMass": 127.6,
        "NumberofNeutrons": 76,
        "NumberofProtons": 52,
        "NumberofElectrons": 52,
    },
    "I": {
        "AtomicNumber": 53,
        "Element": "Iodine",
        "AtomicMass": 126.904,
        "NumberofNeutrons": 74,
        "NumberofProtons": 53,
        "NumberofElectrons": 53,
    },
    "Xe": {
        "AtomicNumber": 54,
        "Element": "Xenon",
        "AtomicMass": 131.293,
        "NumberofNeutrons": 77,
        "NumberofProtons": 54,
        "NumberofElectrons": 54,
    },
    "Cs": {
        "AtomicNumber": 55,
        "Element": "Cesium",
        "AtomicMass": 132.905,
        "NumberofNeutrons": 78,
        "NumberofProtons": 55,
        "NumberofElectrons": 55,
    },
    "Ba": {
        "AtomicNumber": 56,
        "Element": "Barium",
        "AtomicMass": 137.327,
        "NumberofNeutrons": 81,
        "NumberofProtons": 56,
        "NumberofElectrons": 56,
    },
    "La": {
        "AtomicNumber": 57,
        "Element": "Lanthanum",
        "AtomicMass": 138.905,
        "NumberofNeutrons": 82,
        "NumberofProtons": 57,
        "NumberofElectrons": 57,
    },
    "Ce": {
        "AtomicNumber": 58,
        "Element": "Cerium",
        "AtomicMass": 140.116,
        "NumberofNeutrons": 82,
        "NumberofProtons": 58,
        "NumberofElectrons": 58,
    },
    "Pr": {
        "AtomicNumber": 59,
        "Element": "Praseodymium",
        "AtomicMass": 140.908,
        "NumberofNeutrons": 82,
        "NumberofProtons": 59,
        "NumberofElectrons": 59,
    },
    "Nd": {
        "AtomicNumber": 60,
        "Element": "Neodymium",
        "AtomicMass": 144.242,
        "NumberofNeutrons": 84,
        "NumberofProtons": 60,
        "NumberofElectrons": 60,
    },
    "Pm": {
        "AtomicNumber": 61,
        "Element": "Promethium",
        "AtomicMass": 145.0,
        "NumberofNeutrons": 84,
        "NumberofProtons": 61,
        "NumberofElectrons": 61,
    },
    "Sm": {
        "AtomicNumber": 62,
        "Element": "Samarium",
        "AtomicMass": 150.36,
        "NumberofNeutrons": 88,
        "NumberofProtons": 62,
        "NumberofElectrons": 62,
    },
    "Eu": {
        "AtomicNumber": 63,
        "Element": "Europium",
        "AtomicMass": 151.964,
        "NumberofNeutrons": 89,
        "NumberofProtons": 63,
        "NumberofElectrons": 63,
    },
    "Gd": {
        "AtomicNumber": 64,
        "Element": "Gadolinium",
        "AtomicMass": 157.25,
        "NumberofNeutrons": 93,
        "NumberofProtons": 64,
        "NumberofElectrons": 64,
    },
    "Tb": {
        "AtomicNumber": 65,
        "Element": "Terbium",
        "AtomicMass": 158.925,
        "NumberofNeutrons": 94,
        "NumberofProtons": 65,
        "NumberofElectrons": 65,
    },
    "Dy": {
        "AtomicNumber": 66,
        "Element": "Dysprosium",
        "AtomicMass": 162.5,
        "NumberofNeutrons": 97,
        "NumberofProtons": 66,
        "NumberofElectrons": 66,
    },
    "Ho": {
        "AtomicNumber": 67,
        "Element": "Holmium",
        "AtomicMass": 164.93,
        "NumberofNeutrons": 98,
        "NumberofProtons": 67,
        "NumberofElectrons": 67,
    },
    "Er": {
        "AtomicNumber": 68,
        "Element": "Erbium",
        "AtomicMass": 167.259,
        "NumberofNeutrons": 99,
        "NumberofProtons": 68,
        "NumberofElectrons": 68,
    },
    "Tm": {
        "AtomicNumber": 69,
        "Element": "Thulium",
        "AtomicMass": 168.934,
        "NumberofNeutrons": 100,
        "NumberofProtons": 69,
        "NumberofElectrons": 69,
    },
    "Yb": {
        "AtomicNumber": 70,
        "Element": "Ytterbium",
        "AtomicMass": 173.054,
        "NumberofNeutrons": 103,
        "NumberofProtons": 70,
        "NumberofElectrons": 70,
    },
    "Lu": {
        "AtomicNumber": 71,
        "Element": "Lutetium",
        "AtomicMass": 174.967,
        "NumberofNeutrons": 104,
        "NumberofProtons": 71,
        "NumberofElectrons": 71,
    },
    "Hf": {
        "AtomicNumber": 72,
        "Element": "Hafnium",
        "AtomicMass": 178.49,
        "NumberofNeutrons": 106,
        "NumberofProtons": 72,
        "NumberofElectrons": 72,
    },
    "Ta": {
        "AtomicNumber": 73,
        "Element": "Tantalum",
        "AtomicMass": 180.948,
        "NumberofNeutrons": 108,
        "NumberofProtons": 73,
        "NumberofElectrons": 73,
    },
    "W": {
        "AtomicNumber": 74,
        "Element": "Wolfram",
        "AtomicMass": 183.84,
        "NumberofNeutrons": 110,
        "NumberofProtons": 74,
        "NumberofElectrons": 74,
    },
    "Re": {
        "AtomicNumber": 75,
        "Element": "Rhenium",
        "AtomicMass": 186.207,
        "NumberofNeutrons": 111,
        "NumberofProtons": 75,
        "NumberofElectrons": 75,
    },
    "Os": {
        "AtomicNumber": 76,
        "Element": "Osmium",
        "AtomicMass": 190.23,
        "NumberofNeutrons": 114,
        "NumberofProtons": 76,
        "NumberofElectrons": 76,
    },
    "Ir": {
        "AtomicNumber": 77,
        "Element": "Iridium",
        "AtomicMass": 192.217,
        "NumberofNeutrons": 115,
        "NumberofProtons": 77,
        "NumberofElectrons": 77,
    },
    "Pt": {
        "AtomicNumber": 78,
        "Element": "Platinum",
        "AtomicMass": 195.084,
        "NumberofNeutrons": 117,
        "NumberofProtons": 78,
        "NumberofElectrons": 78,
    },
    "Au": {
        "AtomicNumber": 79,
        "Element": "Gold",
        "AtomicMass": 196.967,
        "NumberofNeutrons": 118,
        "NumberofProtons": 79,
        "NumberofElectrons": 79,
    },
    "Hg": {
        "AtomicNumber": 80,
        "Element": "Mercury",
        "AtomicMass": 200.59,
        "NumberofNeutrons": 121,
        "NumberofProtons": 80,
        "NumberofElectrons": 80,
    },
    "Tl": {
        "AtomicNumber": 81,
        "Element": "Thallium",
        "AtomicMass": 204.383,
        "NumberofNeutrons": 123,
        "NumberofProtons": 81,
        "NumberofElectrons": 81,
    },
    "Pb": {
        "AtomicNumber": 82,
        "Element": "Lead",
        "AtomicMass": 207.2,
        "NumberofNeutrons": 125,
        "NumberofProtons": 82,
        "NumberofElectrons": 82,
    },
    "Bi": {
        "AtomicNumber": 83,
        "Element": "Bismuth",
        "AtomicMass": 208.98,
        "NumberofNeutrons": 126,
        "NumberofProtons": 83,
        "NumberofElectrons": 83,
    },
    "Po": {
        "AtomicNumber": 84,
        "Element": "Polonium",
        "AtomicMass": 210.0,
        "NumberofNeutrons": 126,
        "NumberofProtons": 84,
        "NumberofElectrons": 84,
    },
    "At": {
        "AtomicNumber": 85,
        "Element": "Astatine",
        "AtomicMass": 210.0,
        "NumberofNeutrons": 125,
        "NumberofProtons": 85,
        "NumberofElectrons": 85,
    },
    "Rn": {
        "AtomicNumber": 86,
        "Element": "Radon",
        "AtomicMass": 222.0,
        "NumberofNeutrons": 136,
        "NumberofProtons": 86,
        "NumberofElectrons": 86,
    },
    "Fr": {
        "AtomicNumber": 87,
        "Element": "Francium",
        "AtomicMass": 223.0,
        "NumberofNeutrons": 136,
        "NumberofProtons": 87,
        "NumberofElectrons": 87,
    },
    "Ra": {
        "AtomicNumber": 88,
        "Element": "Radium",
        "AtomicMass": 226.0,
        "NumberofNeutrons": 138,
        "NumberofProtons": 88,
        "NumberofElectrons": 88,
    },
    "Ac": {
        "AtomicNumber": 89,
        "Element": "Actinium",
        "AtomicMass": 227.0,
        "NumberofNeutrons": 138,
        "NumberofProtons": 89,
        "NumberofElectrons": 89,
    },
    "Th": {
        "AtomicNumber": 90,
        "Element": "Thorium",
        "AtomicMass": 232.038,
        "NumberofNeutrons": 142,
        "NumberofProtons": 90,
        "NumberofElectrons": 90,
    },
    "Pa": {
        "AtomicNumber": 91,
        "Element": "Protactinium",
        "AtomicMass": 231.036,
        "NumberofNeutrons": 140,
        "NumberofProtons": 91,
        "NumberofElectrons": 91,
    },
    "U": {
        "AtomicNumber": 92,
        "Element": "Uranium",
        "AtomicMass": 238.029,
        "NumberofNeutrons": 146,
        "NumberofProtons": 92,
        "NumberofElectrons": 92,
    },
    "Np": {
        "AtomicNumber": 93,
        "Element": "Neptunium",
        "AtomicMass": 237.0,
        "NumberofNeutrons": 144,
        "NumberofProtons": 93,
        "NumberofElectrons": 93,
    },
    "Pu": {
        "AtomicNumber": 94,
        "Element": "Plutonium",
        "AtomicMass": 244.0,
        "NumberofNeutrons": 150,
        "NumberofProtons": 94,
        "NumberofElectrons": 94,
    },
    "Am": {
        "AtomicNumber": 95,
        "Element": "Americium",
        "AtomicMass": 243.0,
        "NumberofNeutrons": 148,
        "NumberofProtons": 95,
        "NumberofElectrons": 95,
    },
    "Cm": {
        "AtomicNumber": 96,
        "Element": "Curium",
        "AtomicMass": 247.0,
        "NumberofNeutrons": 151,
        "NumberofProtons": 96,
        "NumberofElectrons": 96,
    },
    "Bk": {
        "AtomicNumber": 97,
        "Element": "Berkelium",
        "AtomicMass": 247.0,
        "NumberofNeutrons": 150,
        "NumberofProtons": 97,
        "NumberofElectrons": 97,
    },
    "Cf": {
        "AtomicNumber": 98,
        "Element": "Californium",
        "AtomicMass": 251.0,
        "NumberofNeutrons": 153,
        "NumberofProtons": 98,
        "NumberofElectrons": 98,
    },
    "Es": {
        "AtomicNumber": 99,
        "Element": "Einsteinium",
        "AtomicMass": 252.0,
        "NumberofNeutrons": 153,
        "NumberofProtons": 99,
        "NumberofElectrons": 99,
    },
    "Fm": {
        "AtomicNumber": 100,
        "Element": "Fermium",
        "AtomicMass": 257.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 100,
        "NumberofElectrons": 100,
    },
    "Md": {
        "AtomicNumber": 101,
        "Element": "Mendelevium",
        "AtomicMass": 258.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 101,
        "NumberofElectrons": 101,
    },
    "No": {
        "AtomicNumber": 102,
        "Element": "Nobelium",
        "AtomicMass": 259.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 102,
        "NumberofElectrons": 102,
    },
    "Lr": {
        "AtomicNumber": 103,
        "Element": "Lawrencium",
        "AtomicMass": 262.0,
        "NumberofNeutrons": 159,
        "NumberofProtons": 103,
        "NumberofElectrons": 103,
    },
    "Rf": {
        "AtomicNumber": 104,
        "Element": "Rutherfordium",
        "AtomicMass": 261.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 104,
        "NumberofElectrons": 104,
    },
    "Db": {
        "AtomicNumber": 105,
        "Element": "Dubnium",
        "AtomicMass": 262.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 105,
        "NumberofElectrons": 105,
    },
    "Sg": {
        "AtomicNumber": 106,
        "Element": "Seaborgium",
        "AtomicMass": 266.0,
        "NumberofNeutrons": 160,
        "NumberofProtons": 106,
        "NumberofElectrons": 106,
    },
    "Bh": {
        "AtomicNumber": 107,
        "Element": "Bohrium",
        "AtomicMass": 264.0,
        "NumberofNeutrons": 157,
        "NumberofProtons": 107,
        "NumberofElectrons": 107,
    },
    "Hs": {
        "AtomicNumber": 108,
        "Element": "Hassium",
        "AtomicMass": 267.0,
        "NumberofNeutrons": 159,
        "NumberofProtons": 108,
        "NumberofElectrons": 108,
    },
    "Mt": {
        "AtomicNumber": 109,
        "Element": "Meitnerium",
        "AtomicMass": 268.0,
        "NumberofNeutrons": 159,
        "NumberofProtons": 109,
        "NumberofElectrons": 109,
    },
    "Ds ": {
        "AtomicNumber": 110,
        "Element": "Darmstadtium ",
        "AtomicMass": 271.0,
        "NumberofNeutrons": 161,
        "NumberofProtons": 110,
        "NumberofElectrons": 110,
    },
    "Rg ": {
        "AtomicNumber": 111,
        "Element": "Roentgenium ",
        "AtomicMass": 272.0,
        "NumberofNeutrons": 161,
        "NumberofProtons": 111,
        "NumberofElectrons": 111,
    },
    "Cn ": {
        "AtomicNumber": 112,
        "Element": "Copernicium ",
        "AtomicMass": 285.0,
        "NumberofNeutrons": 173,
        "NumberofProtons": 112,
        "NumberofElectrons": 112,
    },
    "Nh": {
        "AtomicNumber": 113,
        "Element": "Nihonium",
        "AtomicMass": 284.0,
        "NumberofNeutrons": 171,
        "NumberofProtons": 113,
        "NumberofElectrons": 113,
    },
    "Fl": {
        "AtomicNumber": 114,
        "Element": "Flerovium",
        "AtomicMass": 289.0,
        "NumberofNeutrons": 175,
        "NumberofProtons": 114,
        "NumberofElectrons": 114,
    },
    "Mc": {
        "AtomicNumber": 115,
        "Element": "Moscovium",
        "AtomicMass": 288.0,
        "NumberofNeutrons": 173,
        "NumberofProtons": 115,
        "NumberofElectrons": 115,
    },
    "Lv": {
        "AtomicNumber": 116,
        "Element": "Livermorium",
        "AtomicMass": 292.0,
        "NumberofNeutrons": 176,
        "NumberofProtons": 116,
        "NumberofElectrons": 116,
    },
    "Ts": {
        "AtomicNumber": 117,
        "Element": "Tennessine",
        "AtomicMass": 295.0,
        "NumberofNeutrons": 178,
        "NumberofProtons": 117,
        "NumberofElectrons": 117,
    },
    "Og": {
        "AtomicNumber": 118,
        "Element": "Oganesson",
        "AtomicMass": 294.0,
        "NumberofNeutrons": 176,
        "NumberofProtons": 118,
        "NumberofElectrons": 118,
    },
}

def getSymbol(Z):
    return __periodicTableZDict__[str(Z)]["Symbol"]

def getZ(s):
    return int(__periodicTableSymbolDict_[s]["AtomicNumber"])

